{
 "title": "Kubernetes for Prometheus Dashboard EN 20210220",
 "description": "[English version] Update 2020.12.09, full display of kubernetes resources! Including K8S overall resource overview, microservice resource details, Pod resource details and K8S network bandwidth, optimize the display of important indicators. https://github.com",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "origin_prometheus",
    "label": "Data Source",
    "query": {
     "query": "label_values(origin_prometheus)"
    }
   },
   {
    "name": "Node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_info{origin_prometheus=~\"$origin_prometheus\"},node)"
    }
   },
   {
    "name": "NameSpace",
    "label": "NameSpaces",
    "query": {
     "query": "label_values(kube_namespace_labels{origin_prometheus=~\"$origin_prometheus\"},namespace)"
    }
   },
   {
    "name": "Container",
    "label": "Microservice (container name)",
    "query": {
     "query": "label_values(kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",namespace=~\"$NameSpace\"},container)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",namespace=~\"$NameSpace\",container=~\"$Container\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",id=\"/\",node=~\"^$Node$\"}[2m])) / sum (machine_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "CPU Request Rate"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "CPU Limit Rate"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",id=\"/\",node=~\"^$Node$\"}) / sum (machine_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"}) / sum(kube_node_status_capacity_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "Memory Request Rate"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"}) / sum(kube_node_status_capacity_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "Memory Limit Rate"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{origin_prometheus=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})by (node) / sum (container_fs_limit_bytes{origin_prometheus=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})by (node)",
     "legendFormat": "Disk Use %"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "count(kube_pod_info{origin_prometheus=~\"$origin_prometheus\",created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"}) by (node)",
     "legendFormat": "pod number"
    },
    {
     "expr": "kube_node_status_condition{origin_prometheus=~\"$origin_prometheus\",status=\"true\",node=~\"^$Node$\"}  == 1",
     "legendFormat": "status"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",id=\"/\",node=~\"^$Node$\"}[3m])) by (node)"
    },
    {
     "expr": "kube_node_status_capacity_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"} - 0"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",id=\"/\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "kube_node_status_capacity_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"} - 0"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum (container_fs_usage_bytes{origin_prometheus=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum (container_fs_limit_bytes{origin_prometheus=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",id=\"/\",node=~\"^$Node$\"})by (node) / sum (machine_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})by (node)",
     "legendFormat": "Memory usage%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_capacity_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})by (node)",
     "legendFormat": "Memory req%"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_capacity_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})by (node)",
     "legendFormat": "Memory limit%"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",id=\"/\",node=~\"^$Node$\"}[2m]))by (node) / sum (machine_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})by (node)",
     "legendFormat": "CPU usage%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})by (node)",
     "legendFormat": "CPU request%"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})by (node)",
     "legendFormat": "Memory limit%"
    },
    {
     "expr": "sum (container_fs_usage_bytes{origin_prometheus=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})by (node) / sum (container_fs_limit_bytes{origin_prometheus=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})by (node)",
     "legendFormat": "Disk usage%"
    },
    {
     "expr": "sum(kube_node_status_capacity_pods{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})by (node)",
     "legendFormat": "Pod ceiling"
    }
   ]
  },
  {
   "title": "Node resource overview: selected node: [$Node]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Node Memory Ratio",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",id=\"/\",node=~\"^$Node$\"}) / sum (machine_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"}) / sum(kube_node_status_capacity_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "Memory Request Rate"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"}) / sum(kube_node_status_capacity_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "Memory Limit Rate"
    }
   ]
  },
  {
   "title": "Node CPU Ratio",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",id=\"/\",node=~\"^$Node$\"}[2m])) / sum (machine_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "CPU Request Rate"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "CPU Limit Rate"
    }
   ]
  },
  {
   "title": "Node and Pod",
   "type": "bargauge",
   "description": "The number of cluster nodes, the number of node POD, the upper limit of node POD",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{origin_prometheus=~\"$origin_prometheus\"})",
     "legendFormat": "Num Nodes"
    },
    {
     "expr": "count(kube_pod_info{origin_prometheus=~\"$origin_prometheus\",created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"})",
     "legendFormat": "Pod Num"
    },
    {
     "expr": "sum(kube_node_status_capacity_pods{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "Limit Pod"
    }
   ]
  },
  {
   "title": "NameSpace Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "count(kube_pod_info{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"}) by (namespace)"
    },
    {
     "expr": "count(kube_service_info{origin_prometheus=~\"$origin_prometheus\"}) by(namespace)"
    },
    {
     "expr": "count(count(kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\"}) by(container,namespace))by(namespace)"
    },
    {
     "expr": "count(kube_configmap_info{origin_prometheus=~\"$origin_prometheus\"}) by(namespace)",
     "legendFormat": "configmap"
    },
    {
     "expr": "count(kube_secret_info{origin_prometheus=~\"$origin_prometheus\"}) by(namespace)",
     "legendFormat": "secret"
    }
   ]
  },
  {
   "title": "$NameSpace: Network Overview (Associated Nodes and NameSpaces) ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m]))*8",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum (rate (container_network_transmit_bytes_total{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m]))*8",
     "legendFormat": "Send"
    }
   ]
  },
  {
   "title": "Node Memory Information",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (machine_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",id=\"/\",node=~\"^$Node$\"})",
     "legendFormat": "Used Amount"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "Request Amount"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "Limit Amount"
    }
   ]
  },
  {
   "title": "Node CPU Core Number",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "Total Cores"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",id=\"/\",node=~\"^$Node$\"}[2m]))",
     "legendFormat": "Used Amount"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "Request Amount"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{origin_prometheus=~\"$origin_prometheus\",node=~\"^$Node$\"})",
     "legendFormat": "Limit Amount"
    }
   ]
  },
  {
   "title": "Node Storage Information",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{origin_prometheus=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) / sum (container_fs_limit_bytes{origin_prometheus=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})",
     "legendFormat": "Usage Rate"
    },
    {
     "expr": "sum (container_fs_usage_bytes{origin_prometheus=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})",
     "legendFormat": "Used Amount"
    },
    {
     "expr": "sum (container_fs_limit_bytes{origin_prometheus=~\"$origin_prometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})",
     "legendFormat": "Total Amount"
    }
   ]
  },
  {
   "title": "Summary of Microservices and Pod Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Microservice (container name) resource statistics",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container) / (sum(container_spec_cpu_quota{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}/100000) by (container)) * 100"
      },
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container)",
       "legendFormat": "Overall audit usage"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container) * 100"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container) * 100",
       "legendFormat": "Average memory% (RSS)"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
       "legendFormat": "Total memory usage (RSS)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "sum(container_fs_usage_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
      },
      {
       "expr": "count(kube_pod_container_info{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by(container) - 0"
      }
     ]
    },
    {
     "title": "Pod resource details",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\"} == 1"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container, pod) / (sum(container_spec_cpu_quota{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}/100000) by (container, pod)) * 100"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container, pod)",
       "legendFormat": "CPU core usage"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\"}) by (container,pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_cpu_cores{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\"}) by (container,pod)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container, pod)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container, pod) * 100",
       "legendFormat": "wss%"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container, pod)",
       "legendFormat": "wss"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container, pod)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container, pod) * 100",
       "legendFormat": "rss%"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container, pod)",
       "legendFormat": "rss"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\"}) by (container,pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\"}) by (container,pod)"
      },
      {
       "expr": "sum(container_fs_usage_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container,pod)"
      },
      {
       "expr": "kube_pod_container_status_restarts_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\"} - 0"
      },
      {
       "expr": "cass_jvm_heap{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}"
      },
      {
       "expr": "cass_jvm_heap_max{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}"
      },
      {
       "expr": "cass_jvm_noheap{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}"
      },
      {
       "expr": "cass_jvm_noheap_max{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Microservice and Pod resource curve graph",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Microservice (container name) overall CPU usage (maximum 100%)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container) / (sum(container_spec_cpu_quota{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}/100000) by (container)) * 100",
       "legendFormat": "{{ container}}"
      }
     ]
    },
    {
     "title": "Microservice (container name) overall Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container) * 100",
       "legendFormat": "WSS：{{ container }}"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container) * 100",
       "legendFormat": "RSS：{{ container }}"
      }
     ]
    },
    {
     "title": "Microservice (container name) overall memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
       "legendFormat": "WSS：{{ container }}"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
       "legendFormat": "RSS：{{ container }}"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{origin_prometheus=~\"$origin_prometheus\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
       "legendFormat": "limits：{{ container }}"
      }
     ]
    },
    {
     "title": "Pod container CPU usage (associable nodes)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (container, pod) / (sum(container_spec_cpu_quota{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}/100000) by (container, pod)) * 100",
       "legendFormat": "{{ pod }}：{{container}}"
      }
     ]
    },
    {
     "title": "Pod container Memory Usage (node can be associated)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod) * 100",
       "legendFormat": "WSS：{{ pod }}：{{container}}"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod) * 100",
       "legendFormat": "RSS：{{ pod }}：{{container}}"
      },
      {
       "expr": "(cass_jvm_heap{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}) / (cass_jvm_heap_max{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}) * 100",
       "legendFormat": "Heap：{{ pod }}：{{container}}"
      }
     ]
    },
    {
     "title": "Pod container memory usage (associable nodes)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod)",
       "legendFormat": "WSS：{{ pod }}：{{container}}"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod)",
       "legendFormat": "RSS：{{ pod }}：{{container}}"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits_memory_bytes{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",container =~\"$Container\",namespace=~\"$NameSpace\"}) by (container,pod)",
       "legendFormat": "limits：{{ pod }}：{{container}}"
      },
      {
       "expr": "cass_jvm_heap{service=~\"$Container\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",namespace=~\"$NameSpace\"}",
       "legendFormat": "Heap：{{ pod }}：{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Microservice Network Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Microservice (container name) network bandwidth per second (associated node and Pod)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "binbps" }
     ],
     "targets": [
      {
       "expr": "sum (sum (rate (container_network_receive_bytes_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\",namespace=~\"$NameSpace\",pod=~\".*$Container.*\"}[2m])) by (pod)* on(pod)  group_right kube_pod_container_info) by(container) *8",
       "legendFormat": "Inflow:{{ container }}"
      },
      {
       "expr": "sum (sum (rate (container_network_transmit_bytes_total{origin_prometheus=~\"$origin_prometheus\",pod=~\"$Pod\",image!=\"\",name=~\"^k8s_.*\",node=~\"^$Node$\",namespace=~\"$NameSpace\",pod=~\".*$Container.*\"}[2m])) by (pod)* on(pod)  group_right kube_pod_container_info) by(container) *8",
       "legendFormat": "Outflow:{{ container }}"
      }
     ]
    }
   ]
  }
 ]
}